services:
    db:
        image: postgres:16-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: psql_db
            POSTGRES_PORT: 6969
        ports:
            - 6969:6969
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 5s
            retries: 10

        volumes:
            - ./pasql_data:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    pasql_data:
